### ISSUE TITLE
Caractere select page crash

### ISSUE THREAD

**Issue by Faster01** [Earthfiredrake/SWL-Clockwatcher#1]
Hello,
I love Clockwatcher, thank you.
However, since I use it. I have a problem. My game crash on the character select page because of the agens icon, I guess. I would like to remove this option (I do not really need it) how can I do this ? An option for this can be added or solved the issue ?

**Comment by Earthfiredrake** [comment]
As of v1.2.2 the chat command `/setoption efdClockwatcherLoginAlerts false` will disable that feature (which should prevent the crashes). Does require a successful login with the mod enabled, if the crashes are constant let me know and I can provide an alternative (out of game) workaround.

Working on a more permanent solution. Bug is slightly intermittent on my end, so testing is rather slow.

**Comment by Earthfiredrake** [comment]
Believe this was solved at v1.3.0. Forgot to close the issue.
